cafe/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('foods/', views.foods, name='foods'),
    path('order/', views.order, name='order'),
    path('<slug>', views.foods_detail, name='foods_detail'),
    path('<slug>/like', views.like_food, name='like_food'),
    path('<slug>/dislike', views.dislike_food, name='dislike_food'),
    path('<slug>/comment/<pk>/delete', views.delete_comment, name='delete_comment'),
    path('<slug>/comment/<pk>/edit', views.edit_comment, name='edit_comment'),
    path('image/<int:pk>', views.image, name='image'),
]

online_cafe/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('cafe.urls', 'online_cafe'), namespace='cafe')),
    path('users/', include(('users.urls', 'online_cafe'), namespace='users')),
    path('i18n/', include('django.conf.urls.i18n'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out'),
]

cafe/models.py
from django.contrib.auth.models import User
from django.db import models


class Carausel(models.Model):
    image = models.ImageField(upload_to='pics/%y/%m/%d/')


class Food(models.Model):
    title = models.CharField(max_length=255)
    subtitle = models.CharField(max_length=255, )
    category = models.ForeignKey('cafe.Category', on_delete=models.CASCADE)
    image = models.ImageField(default='default_product.png', null=True)
    is_new = models.BooleanField(default=False)
    is_discounted = models.BooleanField(default=False)
    slug = models.SlugField(unique=True)
    date = models.DateField(auto_now=True)
    author = models.ForeignKey(User, default='User', on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='food_likes')
    dislikes = models.ManyToManyField(User, related_name='food_dislikes')

    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count()

    def total_dislikes(self):
        return self.dislikes.count()

    class Meta:
        db_table = 'cafe_foods'


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'cafe_categories'


class Comment(models.Model):
    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.food} - {self.body[:5]}"


class Order(models.Model):
    title = models.CharField(max_length=255)
    sub_title = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    number = models.CharField(max_length=255)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

cafe/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'textarea',
        'size': '40',
        'placeholder': 'Напишите свой комментарий и не забудьте поставить лайк ... '
    }))

    class Meta:
        model = Comment
        fields = ['body', ]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}),
                               label='Введите ваше имя')
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}),
                                label='Создайте пароль')
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}),
                                label='Повторите пароль')

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class SignInForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}),
                               label='Введите имя')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}),
                               label='Введите пароль')

    class Meta:
        model = User
        fields = ['username', 'password']

cafe/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import *
from .forms import CommentForm
from django.db.models import Q


def main(request):
    objects = Carausel.objects.all()
    search = request.GET.get('input')
    object = objects.filter(Q(title__icontains=search) | Q(text__icontains=search)
                            ) if search else objects
    return render(request, 'main.html', {'objects': objects})


def foods(request):
    food = Food.objects.all()
    category = request.GET.get('category')
    search = request.GET.get('input')
    foods = food.filter(Q(title__icontains=search) | Q(text__icontains=search)
                        ) if search else food
    food = food.filter(category=category) if category else food
    return render(request, 'foods.html', {'food': food})


def order(request):
    order = Order.objects.all()
    search = request.GET.get('input')
    return render(request, 'order.html', {'order': order})


def foods_detail(request, slug):
    food = Food.objects.get(slug=slug)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.food = food
            instance.save()
            return redirect('cafe:foods_detail', slug=slug)
    form = CommentForm()
    search = request.GET.get('input')
    foods = food.filter(Q(title__icontains=search) | Q(text__icontains=search)
                        ) if search else food
    return render(request, 'foods_detail.html', {'food': food, 'form': form})


def like_food(request, slug):
    food = Food.objects.get(slug=slug)
    if request.user not in food.likes.all():
        food.likes.add(request.user)
        food.dislikes.remove(request.user)
    elif request.user in food.likes.all():
        food.likes.remove(request.user)
    return redirect('cafe:foods_detail', slug=slug)


def dislike_food(request, slug):
    food = Food.objects.get(slug=slug)
    if request.user not in food.dislikes.all():
        food.dislikes.add(request.user)
        food.likes.remove(request.user)
    elif request.user in food.dislikes.all():
        food.dislikes.remove(request.user)
    return redirect('cafe:foods_detail', slug=slug)


def delete_comment(request, pk, slug):
    comment = Comment.objects.get(pk=pk)
    if request.method == 'POST':
        comment.delete()
        return redirect('cafe:foods_detail', slug=slug)
    return render(request, 'delete_comment.html', {'comment': comment})


def edit_comment(request, pk, slug):
    comment = Comment.objects.get(pk=pk)
    form = CommentForm(request.POST or None, instance=comment)
    if form.is_valid():
        form.save()
        return redirect('cafe:foods_detail', slug=slug)
    return render(request, 'edit_comment.html', {'form': form, 'food': comment.food})


def image(request, pk):
    object = Carausel.objects.get(pk=pk)
    return render(request, 'image.html', {'object': object})

users/views.py
from django.shortcuts import render, redirect
from . import forms
from django.contrib.auth import login, logout


def sign_up(request):
    if request.method == 'POST':
        form = forms.SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:sign_in')
    form = forms.SignUpForm()
    return render(request, 'sign_up.html', {'form': form})


def sign_in(request):
    if request.method == 'POST':
        form = forms.SignInForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('cafe:foods')
    form = forms.SignInForm()
    return render(request, 'sign_in.html', {'form': form})


def sign_out(request):
    logout(request)
    return redirect('cafe:foods')

cafe/templates/categories.html
<div class="tabs is-centered is-fullwidth ">
    <ul>

        {% for category in categories %}
            <li>
                <a href="{% url 'cafe:foods' %}?category={{ category.pk }}"
                   class="navbar-item tabss has-text-weight-bold has-text-weight-medium is-size-5">
                    {{ category }}
                </a>
            </li>
        {% endfor %}
    </ul>
</div>

cafe/templates/delete_comment.html
{% extends 'index.html' %}

{% block content %}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <section class="section ">
    <br>
    <br>
<form action="" class="site-form has-background-light has-text-centered detail" method="post"  style="border-radius: 15px; width: 40%; height: 150px; ">
    {% csrf_token %}
    <br>
    <p class="title is-size-4 mb-4">
        Вы действительно хотите удалить комментарий?
    </p>
    <div class="has-text-centered">
        <button class="button is-success" type="submit">
            Подтвердить
        </button>
        <a href="{% url 'cafe:foods_detail' comment.food.slug%} " class="button is-danger">
            Отмена
        </a>
    </div>
</form>
    <br>
    <br>
    </section>
{% endblock %}

cafe/templates/foods.html
{% extends 'index.html' %}
{% load static %}
{% load categories %}

{% block foods %}
    <br>
    <br>
    <br>


    <section class="section s-1  " style="background-image: url({% static 'uploads/city.jpg' %}); background-attachment: fixed; background-size: cover; background-repeat: no-repeat">
        {% categories %}
        <div class="columns">
                <div class="columns is-multiline is-centered" >
                    {% for foods in food %}
                        <div class="column is-4 mt-3   mx-2" style="border-radius: 10px; width: 350px; background: rgba(20,20,20, 0.5); backdrop-filter: blur(16px)">
                            <div class="card product-card  " style="min-height: auto; min-width: 300px; background: none">
                                <a href="">
                                    <div class="card-image">
                                        <figure class="image" style="">
                                            <img src="{{ foods.image.url }}" alt="Placeholder image" style="height: 250px;">
                                        </figure>
                                        <div class="has-text-right m-3">
                                            {% if foods.is_new %}
                                                <span class="tag is-danger">New!</span>
                                            {% endif %}
                                            {% if foods.is_discounted %}
                                                <span class="tag is-primary">Discount!</span>
                                            {% endif %}
                                        </div>
                                    </div>
                                </a>
                                <div class="card-content" style="background: none">
                                    <div class="media">
                                        <br>
                                        <div class="media-content">
                                            <p class="title is-4 has-text-centered has-text-light has-text-weight-bold">{{ foods }}</p>
                                            <p class="subtitle is-6 has-text-weight-normal  has-text-centered has-text-grey-light"> {{ foods.subtitle }}</p>
                                        </div>
                                    </div>
                                    <div class="columns">
                                        <div class="column"></div>
                                    </div>
                                    <div class="content has-text-weight-bold ">
                                        <a href="{% url 'cafe:foods_detail' foods.slug %}"
                                           class="button foods_detail_button  ">Посмотреть</a>
                                    </div>
                                    <br>

                                    <div class="columns is-centered">
                                        <div class="column is-2">
                                            <div class="columns is-gapless">
                                                <div class="column">
                                                    <ion-icon class="mt-1  " style="color: #cffdc0" name="thumbs-up"></ion-icon>
                                                </div>
                                                <div class="column">
                                                    <span class="ml-2" style="color: #ffffff">{{ foods.total_likes }}</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="column is-2">
                                            <div class="columns is-gapless">
                                                <div class="column">
                                                    <ion-icon class="mt-1 " style="color: #f5bbbb" name="thumbS-down"></ion-icon>
                                                </div>
                                                <div class="column">
                                                    <span class="ml-2" style="color: white">{{ foods.total_dislikes }}</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="column is-2">
                                            <div class="columns is-gapless">
                                                <div class="column">
                                                    <ion-icon class="mt-1 " style="color: #adabab" name="card"></ion-icon>
                                                </div>
                                                <div class="column">
                                                    <span class="ml-2" style="color: white">{{ foods.comment_set.count }}</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
    </section>
{% endblock %}

cafe/templates/foods_detail.html
{% extends 'index.html' %}
{% load static from static %}

{% block content %}
    <section
            style="background-image: url({% static 'uploads/city3.webp' %}); background-attachment: fixed; background-size: cover; background-repeat: no-repeat">

        <br>
        <br>
        <br>
        <br>
        <div class="title has-text-light has-text-centered" >
            {{ food }}
        </div>
        {% if user.is_authenticated %}
            <section class="section">
            <div>
                <div class="columns is-vcentered" >
                    <div class="column is-6" ><img src="{{ food.image.url }}" alt="" class="image is-centered"
                                                  style="min-width: 70%; border-radius: 5px">
                        <br>

                        {% if user not in food.likes.all and user not in food.dislikes.all %}
                            <div class="columns">
                                <div class="column is-1 mx-6">
                                    <form action="{% url 'cafe:like_food' food.slug %}" method="post"
                                          class="has-text-right">
                                        {% csrf_token %}
                                        <button class="button is-rounded" type="submit">
                                            <ion-icon name="thumbs-up"></ion-icon>
                                            <span class="ml-2">{{ food.total_likes }}</span>
                                        </button>
                                    </form>
                                </div>
                                <div class="column is-1 mx-6" >
                                    <form action="{% url 'cafe:dislike_food' food.slug %}" method="post"
                                          class="has-text-right">
                                        {% csrf_token %}
                                        <button class="button is-rounded " type="submit">
                                            <ion-icon name="thumbs-down"></ion-icon>
                                            <span class="ml-2">{{ food.total_dislikes }}</span>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        {% endif %}
                        {% if user  in food.likes.all and user not in food.dislikes.all %}
                            <div class="columns">
                                <div class="column is-1 mx-6">
                                    <form action="{% url 'cafe:like_food' food.slug %}" method="post"
                                          class="has-text-right">
                                        {% csrf_token %}
                                        <button class="button is-success is-rounded" type="submit">
                                            <span class="has-text-light"><ion-icon name="thumbs-up"></ion-icon></span>
                                            <span class="ml-2 has-text-light">{{ food.total_likes }}</span>
                                        </button>
                                    </form>
                                </div>
                                <div class="column is-1 mx-6">
                                    <form action="{% url 'cafe:dislike_food' food.slug %}" method="post"
                                          class="has-text-right">
                                        {% csrf_token %}
                                        <button class="button is-rounded" type="submit">
                                            <ion-icon name="thumbs-down"></ion-icon>
                                            <span class="ml-2">{{ food.total_dislikes }}</span>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        {% endif %}
                        {% if user not in food.likes.all and user  in food.dislikes.all %}
                            <div class="columns">
                                <div class="column is-1 mx-6">
                                    <form action="{% url 'cafe:like_food' food.slug %}" method="post">
                                        {% csrf_token %}
                                        <button class="button is-rounded" type="submit">
                                            <span class="has-text-black"><ion-icon name="thumbs-up"></ion-icon></span>
                                            <span class="ml-2 has-text-black">{{ food.total_likes }}</span>
                                        </button>
                                    </form>
                                </div>
                                <div class="column is-1 mx-6">
                                    <form action="{% url 'cafe:dislike_food' food.slug %}" method="post">
                                        {% csrf_token %}
                                        <button class="button is-danger is-rounded " type="submit">
                                            <span class="has-text-light"><ion-icon name="thumbs-down"></ion-icon></span>
                                            <span class="ml-2 has-text-light">{{ food.total_dislikes }}</span>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        {% endif %}</div>

                    <div class="column is-6 " style="background: rgba(20,20, 20, 0.5); backdrop-filter: blur(16px); border-radius: 8px">
                        {% if not food.comment_set.all %}
                            <div class="has-text-centered has-text-grey-light is-5 mx-2">
                                Нет комментариев. Вы можете стать первым ...
                            </div>

                        {% endif %}
                        <form class="comment" enctype="multipart/form-data" method="post" style="color: gainsboro">
                            {% csrf_token %}
                            {{ form }}
                            <button class="button is-success is-fullwidth has-text-weight-bold mt-3">
                                Сохранить
                            </button>
                        </form>
                        <br>
                    </div>
                </div>
</div>
                <div class="title  is-3 mb-6">
                    {% for comment in food.comment_set.all %}
                        <article class="message " style="background: rgba(20,20, 20, 0.5); backdrop-filter: blur(16px);">
                            {% if user == comment.user %}
                                <div class="message-header">
                                    Было добавлено {{ comment.user }} в {{ comment.date_added }}
                                    <div class="has-text-left  is-size-5">
                                        <a href="{% url 'cafe:edit_comment' slug=food.slug pk=comment.pk %}"
                                           class="button is-size-5 "
                                           style="text-decoration: none; background: none; border: none ">
                                            <span class="has-text-info"><ion-icon
                                                    name="create-outline"></ion-icon></span>

                                        </a>
                                        <a href="{% url 'cafe:delete_comment' slug=food.slug pk=comment.pk %}"
                                           class="button is-size-5" style="text-decoration: none; background: none; border: none  ">
                                            <span class="has-text-danger"><ion-icon
                                                    name="trash-outline"></ion-icon></span>
                                        </a>
                                    </div>
                                </div>
                            {% else %}
                                Было добавлено {{ comment.user }} в {{ comment.date_added }}
                            {% endif %}
                            <div class="message-body " style="color: lightgrey">{{ comment.body }}</div>
                        </article>
                    {% endfor %}
                </div>


            </section>
        {% else %}
            <section class="section">
                <div class="columns is-vcentered">
                    <div class="column  is-6"><img src="{{ food.image.url }}" alt="" class="image is-centered"
                                                   style="min-width: 70%; border-radius: 5px;">
                        <br>
                    </div>
                    <div class="column" >
                        <div class="title has-text-centered has-text-light ">Чтобы добавить свой комментарий и поставить
                            лайк зарегистрируйтесь
                            <br>
                            <br>
                            <a href="{% url 'users:sign_up' %}" class="button is-rounded is-success ">
                                Зарегистрироваться</a>
                        </div>

                    </div>
                </div>
                <div class="title  is-3 mb-6 ">
                    {% for comment in food.comment_set.all %}
                        <article class="message " style="background: rgba(20,20, 20, 0.5); backdrop-filter: blur(16px);">
                            {% if user == comment.user %}
                                <div class="message-header" style="color: lightgrey">
                                    Было добавлено {{ comment.user }} в {{ comment.date_added }}
                                     <div class="has-text-left  is-size-5">
                                        <a href="{% url 'cafe:edit_comment' slug=food.slug pk=comment.pk %}"
                                           class="button is-size-5 "
                                           style="text-decoration: none; background: none; border: none ">
                                            <span class="has-text-info"><ion-icon
                                                    name="create-outline"></ion-icon></span>

                                        </a>
                                        <a href="{% url 'cafe:delete_comment' slug=food.slug pk=comment.pk %}"
                                           class="button is-size-5" style="text-decoration: none; background: none; border: none  ">
                                            <span class="has-text-danger"><ion-icon
                                                    name="trash-outline"></ion-icon></span>
                                        </a>
                                    </div>
                                </div>
                            {% else %}
                                <div style="color: lightgrey">
                                Было добавлено {{ comment.user }} в {{ comment.date_added }}</div>
                            {% endif %}
                            <div class="message-body" style="color: lightgrey" >{{ comment.body }}</div>
                        </article>
                    {% endfor %}
                </div>

                </div>
            </section>
        {% endif %}
    </section>
{% endblock %}

cafe/templates/index.html
{% load static %}
{% load categories %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Restaurant Chinor</title>
    <link rel="icon" href='{% static 'uploads/shortcut-icon.png' %}' type="image/gif" sizes="16x16">
    <link rel="stylesheet" href="{% static 'static/bulma.css' %}">
    <link rel="stylesheet" href="{% static 'static/style.css' %}">
    <link
            rel="stylesheet"
            href="https://unpkg.com/swiper/swiper-bundle.min.css"
    />
    <link href="https://fonts.googleapis.com/css2?family=League+Spartan&display=swap" rel="stylesheet">
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</head>
<style>
</style>
<body>
<div class="navbar is-fullwidth p-1 "
     style=" width: 100%; position: fixed;  height: 70px; background: linear-gradient(145deg, #d51111 0, #c40101 50%, #f53838 100%);">
    <div class="navbar-brand" style="opacity: 100%;">
        <p class="title chinor is-1 mx-6 mt-1  has-text-light">Chinor</p>
        <a href="{% url 'cafe:main' %}" class="title about has-text-weight-bold is-4 mt-4 mx-3 has-text-light">О
            Нас</a>
        <a href="{% url 'cafe:foods' %}"
           class="title about has-text-weight-bold is-4 mt-4 mx-3 has-text-light">Блюда</a>
        <a href="{% url 'cafe:order' %}"
           class="title has-text-weight-bold about is-4 mt-4 mx-3  has-text-light">Заказать</a>
        <a href=""></a>
        <span class="navbar-burger mt-2" data-target="navbarMenuHeroC" onclick="toggleBurger()" style="color: red; ">
            <span></span>
            <span></span>
            <span></span>
          </span>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-item" style="">
            <form action="{% url 'cafe:foods' %} " method="get" class=" form-1 mt-4 " style="opacity: 100%;">
                <input type="search" placeholder="Поиск по сайту">
                <i class="fa fa-search">
                    <ion-icon name="search"></ion-icon>
                </i>
            </form>
        </div>

        <div class="navbar-end">

            {% if user.is_authenticated  %}
                <span class="navbar-item " style="opacity: 100%;">
                   <a class="button bt-1 is-disabled is-white has-text-black has-text-weight-bold  mt-1  ">
                        <span class="mx-3"><ion-icon name="person"></ion-icon></span> {{ user }}
                   </a>
                </span>

            {% else %}
            <span class="navbar-item" style="opacity: 100%;">
                <a class="button log-in bt-1 is-disabled is-white has-text-black has-text-success has-text-weight-bold  mt-1  "
                   href="{% url 'users:sign_in' %}">
                        <span class="mx-2 "><ion-icon name="log-in"></ion-icon></span><span class="mt-1">Войти</span>
                   </a>
                </span>
        {% endif %}
            {% if user.is_authenticated %}
                <span class="navbar-item" style="opacity: 100%;">
                <a class="button  bt-1 is-disabled is-white has-text-black has-text-danger has-text-weight-bold  mt-1  "
                   href="{% url 'users:sign_out' %}">
                         <span class="mt-1">Выйти</span> <span class="mx-2"><ion-icon name="log-out"></ion-icon></span>
                   </a>
                </span>
            {% endif %}
        </div>
    </div>
</div>
{% block about %}
{% endblock %}
{% block foods %}
{% endblock %}
{% block order %}
{% endblock %}
{% block auth %}
{% endblock %}
{% block content %}
{% endblock %}
<script>
    function openTab(event, tabName) {
        event.preventDefault()

        let i, x, tablinks;

        x = document.getElementsByClassName("content-tab");
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tab");
        for (i = 0; i < x.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" is-active", "");
        }
        document.getElementById(tabName).style.display = "block";
        event.currentTarget.className += " is-active";

    }

    function toggleBurger() {
        document.querySelector('.navbar-burger').classList.toggle('is-active')
        document.querySelector('.navbar-menu').classList.toggle('is-active')

    }
</script>
</body>
</html>